/**
 * Question Template
 *
 * Default 54 questions for Tableau Cloud migration projects.
 * Sourced from tableau-migration-checklist-pro.html
 */

const questionTemplate = [
  {
    id: 'q1',
    section: 'Security',
    questionText: 'SecOps are aware of the migration and have signed this off? Confirm',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 1,
    metadata: {},
  },
  {
    id: 'q2',
    section: 'Security',
    questionText: 'Has data connectivity and access to data sources been confirmed?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 2,
    metadata: {},
  },
  {
    id: 'q3',
    section: 'Security',
    questionText: 'Provide detail of the expected connections',
    questionType: 'textInput',
    answer: null,
    completed: false,
    order: 3,
    metadata: {},
  },
  {
    id: 'q4',
    section: 'Communications',
    questionText: 'Has an internal communication strategy been confirmed?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 4,
    metadata: {},
  },
  {
    id: 'q5',
    section: 'Communications',
    questionText: 'Communication assistance offered?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 5,
    metadata: {},
  },
  {
    id: 'q6',
    section: 'Communications',
    questionText: 'Have resources been requested and assigned internally?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 6,
    metadata: {},
  },
  {
    id: 'q7',
    section: 'Communications',
    questionText: 'Are your developers aware of a potential change freeze?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 7,
    metadata: {},
  },
  {
    id: 'q8',
    section: 'Stakeholders',
    questionText: 'Provide a list of stakeholders and available resources for migration',
    questionType: 'textInput',
    answer: null,
    completed: false,
    order: 8,
    metadata: {},
  },
  {
    id: 'q9',
    section: 'Access & Connectivity',
    questionText: 'How is Interworks connecting to your Tableau Server?',
    questionType: 'textInput',
    answer: null,
    completed: false,
    order: 9,
    metadata: {},
  },
  {
    id: 'q10',
    section: 'Access & Connectivity',
    questionText: 'Has the jumpbox been built to a required specification?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 10,
    metadata: {},
  },
  {
    id: 'q11',
    section: 'Access & Connectivity',
    questionText: 'Has access been provided to IW Consultants?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 11,
    metadata: {},
  },
  {
    id: 'q12',
    section: 'Access & Connectivity',
    questionText: 'Has PowerShell been enabled with Admin rights?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 12,
    metadata: {},
  },
  {
    id: 'q13',
    section: 'Access & Connectivity',
    questionText: 'Confirm file transfer methods',
    questionType: 'textInput',
    answer: null,
    completed: false,
    order: 13,
    metadata: {},
  },
  {
    id: 'q14',
    section: 'Access & Connectivity',
    questionText: 'Is Tableau Desktop available on the Jumpbox?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 14,
    metadata: {},
  },
  {
    id: 'q15',
    section: 'Access & Connectivity',
    questionText: 'Tool installed on Jumpbox?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 15,
    metadata: {},
  },
  {
    id: 'q16',
    section: 'Access & Connectivity',
    questionText: 'Server and Cloud PATS generated and connectivity confirmed?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 16,
    metadata: {},
  },
  {
    id: 'q17',
    section: 'Tableau Server',
    questionText: 'Are PAT tokens enabled on Tableau Server?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 17,
    metadata: {},
  },
  {
    id: 'q18',
    section: 'Tableau Server',
    questionText: 'Is Tableau Repository readonly access enabled?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 18,
    metadata: {},
  },
  {
    id: 'q19',
    section: 'Tableau Server',
    questionText: 'Has the Runbook been installed and an overview provided?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 19,
    metadata: {},
  },
  {
    id: 'q20',
    section: 'Tableau Server',
    questionText: 'Is there a time delay for client to review Runbook?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 20,
    metadata: {},
  },
  {
    id: 'q21',
    section: 'Tableau Server',
    questionText: 'Expected Date for Runbook review completion',
    questionType: 'dateInput',
    answer: null,
    completed: false,
    order: 21,
    metadata: {},
  },
  {
    id: 'q22',
    section: 'Tableau Server',
    questionText: 'Has any housekeeping taken place?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 22,
    metadata: {},
  },
  {
    id: 'q23',
    section: 'Tableau Server',
    questionText: 'Any initial project exclusions to be made aware of initially?',
    questionType: 'yesNo',
    options: ['Yes', 'No'],
    answer: null,
    completed: false,
    order: 23,
    metadata: {},
  },
  {
    id: 'q24',
    section: 'Tableau Server',
    questionText: 'Do all users have a valid email address?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 24,
    metadata: {},
  },
  {
    id: 'q25',
    section: 'Pre Flight Checks',
    questionText: 'Is Row Level Security used extensively in Workbooks?',
    questionType: 'yesNo',
    options: ['Yes', 'No'],
    answer: null,
    completed: false,
    order: 25,
    metadata: {},
  },
  {
    id: 'q26',
    section: 'Pre Flight Checks',
    questionText: 'Are you aware of any URL actions that may be present?',
    questionType: 'yesNo',
    options: ['Yes', 'No'],
    answer: null,
    completed: false,
    order: 26,
    metadata: {},
  },
  {
    id: 'q27',
    section: 'Pre Flight Checks',
    questionText: 'Are you aware of any fonts that are non web conformant?',
    questionType: 'yesNo',
    options: ['Yes', 'No'],
    answer: null,
    completed: false,
    order: 27,
    metadata: {},
  },
  {
    id: 'q28',
    section: 'Pre Flight Checks',
    questionText:
      'Pre flight checks will identify the above. Any RLS or URL Actions will need to be updated post migration by power users/developers. Please confirm.',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 28,
    metadata: {
      isFullWidth: true,
    },
  },
  {
    id: 'q29',
    section: 'Pre Flight Checks',
    questionText: 'Pre flight checks performed and delivered to client',
    questionType: 'dateInput',
    answer: null,
    completed: false,
    order: 29,
    metadata: {},
  },
  {
    id: 'q30',
    section: 'Pre Flight Checks',
    questionText: 'Has client reviewed Pre flight checks documentation?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 30,
    metadata: {},
  },
  {
    id: 'q31',
    section: 'Pre Flight Checks',
    questionText: 'Do we expect any delay on starting the migration based on the pre flight checks?',
    questionType: 'yesNo',
    options: ['Yes', 'No'],
    answer: null,
    completed: false,
    order: 31,
    metadata: {
      hasConditionalDate: true,
    },
  },
  {
    id: 'q32',
    section: 'Tableau Cloud',
    questionText: 'Has the Tableau/Salesforce paperwork been signed?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 32,
    metadata: {
      hasConditionalInput: true,
    },
  },
  {
    id: 'q33',
    section: 'Tableau Cloud',
    questionText: 'Confirm Tableau Cloud SKU type',
    questionType: 'dropdown',
    options: ['Standard', 'Enterprise', 'Tableau +'],
    answer: null,
    completed: false,
    order: 33,
    metadata: {},
  },
  {
    id: 'q34',
    section: 'Tableau Cloud',
    questionText: 'Number of Expected Sites',
    questionType: 'dropdown',
    options: ['1', '2', '3', '4', '5', '+5'],
    answer: null,
    completed: false,
    order: 34,
    metadata: {},
  },
  {
    id: 'q35',
    section: 'Tableau Cloud',
    questionText: 'Has Authentication method been confirmed?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 35,
    metadata: {
      hasConditionalInput: true,
    },
  },
  {
    id: 'q36',
    section: 'Tableau Cloud',
    questionText: 'If SSO - Is app built and applied?',
    questionType: 'yesNo',
    options: ['Yes', 'N/A'],
    answer: null,
    completed: false,
    order: 36,
    metadata: {},
  },
  {
    id: 'q37',
    section: 'Tableau Cloud',
    questionText: 'Is any conditional access expected?',
    questionType: 'yesNo',
    options: ['Yes', 'No'],
    answer: null,
    completed: false,
    order: 37,
    metadata: {},
  },
  {
    id: 'q38',
    section: 'Tableau Cloud',
    questionText: 'Is SCIM being implemented?',
    questionType: 'yesNo',
    options: ['Yes', 'No'],
    answer: null,
    completed: false,
    order: 38,
    metadata: {},
  },
  {
    id: 'q39',
    section: 'Tableau Cloud',
    questionText: 'Are the user groups on the authentication app built?',
    questionType: 'yesNo',
    options: ['Yes', 'No'],
    answer: null,
    completed: false,
    order: 39,
    metadata: {},
  },
  {
    id: 'q40',
    section: 'Tableau Cloud',
    questionText: 'Group Remapping required?',
    questionType: 'yesNo',
    options: ['Yes', 'No'],
    answer: null,
    completed: false,
    order: 40,
    metadata: {},
  },
  {
    id: 'q41',
    section: 'Tableau Cloud',
    questionText: 'Any project hierarchy adjustments',
    questionType: 'yesNo',
    options: ['Yes', 'No'],
    answer: null,
    completed: false,
    order: 41,
    metadata: {},
  },
  {
    id: 'q42',
    section: 'Tableau Cloud',
    questionText: 'Have InterWorks engineers been provided access to Tableau Server as Site Admin Creators?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 42,
    metadata: {},
  },
  {
    id: 'q43',
    section: 'Tableau Cloud',
    questionText: 'Are you expecting to use Custom Domains in Tableau Cloud?',
    questionType: 'yesNo',
    options: ['Yes', 'No'],
    answer: null,
    completed: false,
    order: 43,
    metadata: {},
  },
  {
    id: 'q44',
    section: 'Tableau Cloud',
    questionText: 'Additional notes for Tableau Cloud',
    questionType: 'textInput',
    answer: null,
    completed: false,
    order: 44,
    metadata: {},
  },
  {
    id: 'q45',
    section: 'Tableau Bridge',
    questionText: 'Do you require the use of Tableau Bridge?',
    questionType: 'yesNo',
    options: ['Yes', 'No'],
    answer: null,
    completed: false,
    order: 45,
    metadata: {},
  },
  {
    id: 'q46',
    section: 'Tableau Bridge',
    questionText: 'Have the Bridge Servers been requested and built?',
    questionType: 'yesNo',
    options: ['Yes', 'No'],
    answer: null,
    completed: false,
    order: 46,
    metadata: {},
  },
  {
    id: 'q47',
    section: 'Tableau Bridge',
    questionText: 'If No - Expected turnaround/Date',
    questionType: 'dateInput',
    answer: null,
    completed: false,
    order: 47,
    metadata: {},
  },
  {
    id: 'q48',
    section: 'Tableau Bridge',
    questionText: 'Has any testing been done?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 48,
    metadata: {},
  },
  {
    id: 'q49',
    section: 'Tableau Bridge',
    questionText: 'Is the Bridge client running in service mode?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 49,
    metadata: {},
  },
  {
    id: 'q50',
    section: 'Tableau Bridge',
    questionText: 'Will the bridge server be accessed via a service account?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 50,
    metadata: {},
  },
  {
    id: 'q51',
    section: 'Tableau Bridge',
    questionText: 'Will the data sources be using Windows Auth?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 51,
    metadata: {},
  },
  {
    id: 'q52',
    section: 'Tableau Bridge',
    questionText: 'Flatfiles will require a full UNC filepath when using Bridge. Confirm',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 52,
    metadata: {},
  },
  {
    id: 'q53',
    section: 'Cloud Data Sources',
    questionText: 'Is Private Connect required?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 53,
    metadata: {},
  },
  {
    id: 'q54',
    section: 'Cloud Data Sources',
    questionText: 'Is IP whitelisting required and completed?',
    questionType: 'checkbox',
    answer: null,
    completed: false,
    order: 54,
    metadata: {},
  },
  {
    id: 'q55',
    section: 'Cloud Data Sources',
    questionText: 'What authentication is used to Cloud Data Sources',
    questionType: 'textInput',
    answer: null,
    completed: false,
    order: 55,
    metadata: {},
  },
];

module.exports = questionTemplate;
